[package]
name = "day_12_js_abacus_framework_io"
version = "0.1.0"
edition = "2024"

[dependencies]
puzzler ={ workspace = true }
regex = { workspace = true }
serde ={ workspace = true }
serde_json ={ workspace = true }